import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Footer from '../components/component/Footer/Footer';
import Hadder from '../components/component/navigation/Hadder';
import FooterTop from './../components/component/Footer/FooterTop';
import { TokenProvider } from "../context/SaveToken";
import { Toaster } from "@/components/ui/toaster"
import { CartProvider } from './../context/Cart';

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange >
          <TokenProvider>
            <CartProvider>
              <Hadder />
              {children}
              <Toaster />
              <FooterTop />
              <Footer />
            </CartProvider>
          </TokenProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}